name: ps3netsrv
version: "1.0"
summary: ps3netsrv
description: |
  ps3netsrv allows you to share files with your PS3 running CFW and Multiman or Webman
confinement: strict
grade: stable


apps:
  ps3netsrv:
    command: ps3netsrv
    plugs: [home, network-bind]

parts:
  ps3netsrv:
    plugin: make
    source-type: git
    source: https://github.com/8none1/ps3netsrv
    artifacts: [ps3netsrv]


